version: '3.8'

service:
order-app:
build: .
container_name: order-container
ports:
   -"5000:5000"
restart: always
environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
depends_on:
      - mysql  # Ensure MySQL starts before Spring Boot
networks:
      - spring-network

  # MySQL Database
mysql:
    image: mysql:8.0  # Use MySQL image from Docker Hub
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_service
    ports:
      - "3362:3306"  # Expose MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - spring-network

# Define a custom Docker network for inter-service communication
networks:
  spring-network:
    driver: bridge

volumes:
  mysql_data:


   